2022-12-04 09:10:47,498 - reindex - INFO - Reindex:query :{"source": {"index": "map-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"indexed_time": {"gte": 1668979368306, "lte": 1668979378306, "boost": 2.0}}}}, "dest": {"index": "map-2022-11-21"}}
2022-12-04 09:10:47,499 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112144948, "lte": 1670112154948, "boost": 2.0}}}}, "dest": {"index": "inews2022-12-04"}}
2022-12-04 09:10:47,499 - reindex - INFO - Reindex:query :{"source": {"index": "rtp-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112548132, "lte": 1670112558132, "boost": 2.0}}}}, "dest": {"index": "rtp-2022-12-04"}}
2022-12-04 09:10:47,503 - reindex - ERROR - Reindex:check_failure (sqlite3.OperationalError) no such column: failurs.query
[SQL: SELECT failurs.id AS failurs_id, failurs.start_time AS failurs_start_time, failurs.end_time AS failurs_end_time, failurs.index_name AS failurs_index_name, failurs."query" AS failurs_query 
FROM failurs]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-12-04 09:10:47,517 - reindex - INFO - reindex result {"took": 13, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:10:47,941 - reindex - INFO - reindex result {"took": 434, "timed_out": false, "total": 370, "updated": 370, "created": 0, "deleted": 0, "batches": 4, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:10:48,508 - reindex - WARNING - Reindex:reindex  (sqlite3.OperationalError) table failurs has no column named query
[SQL: INSERT INTO failurs (start_time, end_time, index_name, "query") VALUES (?, ?, ?, ?)]
[parameters: ('1670112144948', 1670112154948, 'inews*', '{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112144948, "lte": 1670112154948, "boost": 2.0}}}}, "dest": {"index": "inews2022-12-04"}}')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-12-04 09:10:52,507 - reindex - ERROR - Reindex:check_failure (sqlite3.OperationalError) no such column: failurs.query
[SQL: SELECT failurs.id AS failurs_id, failurs.start_time AS failurs_start_time, failurs.end_time AS failurs_end_time, failurs.index_name AS failurs_index_name, failurs."query" AS failurs_query 
FROM failurs]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-12-04 09:10:52,535 - reindex - INFO - Reindex:query :{"source": {"index": "map-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"indexed_time": {"gte": 1668979485569, "lte": 1668979495569, "boost": 2.0}}}}, "dest": {"index": "map-2022-11-21"}}
2022-12-04 09:10:52,551 - reindex - INFO - reindex result {"took": 10, "timed_out": false, "total": 1, "updated": 1, "created": 0, "deleted": 0, "batches": 1, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:10:52,948 - reindex - INFO - Reindex:query :{"source": {"index": "rtp-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112558132, "lte": 1670112568132, "boost": 2.0}}}}, "dest": {"index": "rtp-2022-12-04"}}
2022-12-04 09:10:52,977 - reindex - INFO - reindex result {"took": 25, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:10:53,511 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112154948, "lte": 1670112164948, "boost": 2.0}}}}, "dest": {"index": "inews2022-12-04"}}
2022-12-04 09:10:53,530 - reindex - INFO - reindex result {"took": 15, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:10:57,511 - reindex - ERROR - Reindex:check_failure (sqlite3.OperationalError) no such column: failurs.query
[SQL: SELECT failurs.id AS failurs_id, failurs.start_time AS failurs_start_time, failurs.end_time AS failurs_end_time, failurs.index_name AS failurs_index_name, failurs."query" AS failurs_query 
FROM failurs]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-12-04 09:10:57,555 - reindex - INFO - Reindex:query :{"source": {"index": "map-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"indexed_time": {"gte": 1668979495569, "lte": 1668979505569, "boost": 2.0}}}}, "dest": {"index": "map-2022-11-21"}}
2022-12-04 09:10:57,568 - reindex - INFO - reindex result {"took": 9, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:10:57,991 - reindex - INFO - Reindex:query :{"source": {"index": "rtp-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112607987, "lte": 1670112617987, "boost": 2.0}}}}, "dest": {"index": "rtp-2022-12-04"}}
2022-12-04 09:10:58,248 - reindex - INFO - reindex result {"took": 251, "timed_out": false, "total": 266, "updated": 266, "created": 0, "deleted": 0, "batches": 3, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:10:59,510 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112166684, "lte": 1670112176684, "boost": 2.0}}}}, "dest": {"index": "inews2022-12-04"}}
2022-12-04 09:10:59,511 - reindex - INFO - Reindex:query :{"source": {"index": "rtp-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112617987, "lte": 1670112627987, "boost": 2.0}}}}, "dest": {"index": "rtp-2022-12-04"}}
2022-12-04 09:10:59,515 - reindex - INFO - Reindex:query :{"source": {"index": "map-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"indexed_time": {"gte": 1668979522990, "lte": 1668979532990, "boost": 2.0}}}}, "dest": {"index": "map-2022-11-21"}}
2022-12-04 09:10:59,529 - reindex - INFO - reindex result {"took": 11, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:10:59,531 - reindex - INFO - reindex result {"took": 11, "timed_out": false, "total": 2, "updated": 2, "created": 0, "deleted": 0, "batches": 1, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:00,521 - reindex - ERROR - Reindex:reindex error elastic reindex ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:04,521 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112166684, "lte": "1670112176684", "boost": 2.0}}}}, "dest": {"index": "2022-12-04"}}
2022-12-04 09:11:04,535 - reindex - INFO - Reindex:query :{"source": {"index": "map-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"indexed_time": {"gte": 1668979532990, "lte": 1668979542990, "boost": 2.0}}}}, "dest": {"index": "map-2022-11-21"}}
2022-12-04 09:11:04,543 - reindex - INFO - Reindex:query :{"source": {"index": "rtp-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112668110, "lte": 1670112678110, "boost": 2.0}}}}, "dest": {"index": "rtp-2022-12-04"}}
2022-12-04 09:11:04,550 - reindex - INFO - reindex result {"took": 9, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:04,837 - reindex - INFO - reindex result {"took": 290, "timed_out": false, "total": 405, "updated": 405, "created": 0, "deleted": 0, "batches": 5, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:05,523 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112176684, "lte": 1670112186684, "boost": 2.0}}}}, "dest": {"index": "inews2022-12-04"}}
2022-12-04 09:11:05,525 - reindex - ERROR - proplem index failure ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:06,561 - reindex - ERROR - Reindex:reindex error elastic reindex ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:09,579 - reindex - INFO - Reindex:query :{"source": {"index": "map-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"indexed_time": {"gte": 1668979837546, "lte": 1668979847546, "boost": 2.0}}}}, "dest": {"index": "map-2022-11-21"}}
2022-12-04 09:11:09,599 - reindex - INFO - reindex result {"took": 14, "timed_out": false, "total": 1, "updated": 1, "created": 0, "deleted": 0, "batches": 1, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:09,841 - reindex - INFO - Reindex:query :{"source": {"index": "rtp-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112678110, "lte": 1670112688110, "boost": 2.0}}}}, "dest": {"index": "rtp-2022-12-04"}}
2022-12-04 09:11:09,855 - reindex - INFO - reindex result {"took": 9, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:10,556 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112166684, "lte": "1670112176684", "boost": 2.0}}}}, "dest": {"index": "2022-12-04"}}
2022-12-04 09:11:11,558 - reindex - ERROR - proplem index failure ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:11,559 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112176684, "lte": "1670112186684", "boost": 2.0}}}}, "dest": {"index": "2022-12-04"}}
2022-12-04 09:11:11,567 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112186684, "lte": 1670112196684, "boost": 2.0}}}}, "dest": {"index": "inews2022-12-04"}}
2022-12-04 09:11:11,646 - reindex - INFO - reindex result {"took": 42, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:12,563 - reindex - ERROR - proplem index failure ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:14,603 - reindex - INFO - Reindex:query :{"source": {"index": "map-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"indexed_time": {"gte": 1668979847546, "lte": 1668979857546, "boost": 2.0}}}}, "dest": {"index": "map-2022-11-21"}}
2022-12-04 09:11:14,638 - reindex - INFO - reindex result {"took": 22, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:14,891 - reindex - INFO - Reindex:query :{"source": {"index": "rtp-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112728015, "lte": 1670112738015, "boost": 2.0}}}}, "dest": {"index": "rtp-2022-12-04"}}
2022-12-04 09:11:15,124 - reindex - INFO - reindex result {"took": 229, "timed_out": false, "total": 301, "updated": 301, "created": 0, "deleted": 0, "batches": 4, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:16,683 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112199189, "lte": 1670112209189, "boost": 2.0}}}}, "dest": {"index": "inews2022-12-04"}}
2022-12-04 09:11:17,569 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112166684, "lte": "1670112176684", "boost": 2.0}}}}, "dest": {"index": "2022-12-04"}}
2022-12-04 09:11:17,692 - reindex - ERROR - Reindex:reindex error elastic reindex ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:18,571 - reindex - ERROR - proplem index failure ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:18,571 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112176684, "lte": "1670112186684", "boost": 2.0}}}}, "dest": {"index": "2022-12-04"}}
2022-12-04 09:11:19,575 - reindex - ERROR - proplem index failure ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:19,662 - reindex - INFO - Reindex:query :{"source": {"index": "map-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"indexed_time": {"gte": 1668980514905, "lte": 1668980524905, "boost": 2.0}}}}, "dest": {"index": "map-2022-11-21"}}
2022-12-04 09:11:19,701 - reindex - INFO - reindex result {"took": 33, "timed_out": false, "total": 1, "updated": 1, "created": 0, "deleted": 0, "batches": 1, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:20,127 - reindex - INFO - Reindex:query :{"source": {"index": "rtp-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112738015, "lte": 1670112748015, "boost": 2.0}}}}, "dest": {"index": "rtp-2022-12-04"}}
2022-12-04 09:11:20,191 - reindex - INFO - reindex result {"took": 51, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:22,695 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112209189, "lte": 1670112219189, "boost": 2.0}}}}, "dest": {"index": "inews2022-12-04"}}
2022-12-04 09:11:23,729 - reindex - ERROR - Reindex:reindex error elastic reindex ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:24,582 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112166684, "lte": "1670112176684", "boost": 2.0}}}}, "dest": {"index": "2022-12-04"}}
2022-12-04 09:11:24,703 - reindex - INFO - Reindex:query :{"source": {"index": "map-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"indexed_time": {"gte": 1668980524905, "lte": 1668980534905, "boost": 2.0}}}}, "dest": {"index": "map-2022-11-21"}}
2022-12-04 09:11:24,766 - reindex - INFO - reindex result {"took": 39, "timed_out": false, "total": 0, "updated": 0, "created": 0, "deleted": 0, "batches": 0, "version_conflicts": 0, "noops": 0, "retries": {"bulk": 0, "search": 0}, "throttled_millis": 0, "requests_per_second": -1.0, "throttled_until_millis": 0, "failures": []}
2022-12-04 09:11:25,211 - reindex - INFO - Reindex:query :{"source": {"index": "rtp-*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112788029, "lte": 1670112798029, "boost": 2.0}}}}, "dest": {"index": "rtp-2022-12-04"}}
2022-12-04 09:11:25,585 - reindex - ERROR - proplem index failure ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:25,585 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112176684, "lte": "1670112186684", "boost": 2.0}}}}, "dest": {"index": "2022-12-04"}}
2022-12-04 09:11:26,225 - reindex - ERROR - Reindex:reindex error elastic reindex ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:26,589 - reindex - ERROR - proplem index failure ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:26,589 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112199189, "lte": "1670112209189", "boost": 2.0}}}}, "dest": {"index": "2022-12-04"}}
2022-12-04 09:11:27,593 - reindex - ERROR - proplem index failure ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:27,593 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112209189, "lte": "1670112219189", "boost": 2.0}}}}, "dest": {"index": "2022-12-04"}}
2022-12-04 09:11:28,596 - reindex - ERROR - proplem index failure ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='192.168.10.110', port=9201): Read timed out. (read timeout=1))
2022-12-04 09:11:28,731 - reindex - INFO - Reindex:query :{"source": {"index": "inews*", "size": 100, "remote": {"host": "http://192.168.10.124:9201"}, "query": {"range": {"info.index_time": {"gte": 1670112219189, "lte": 1670112229189, "boost": 2.0}}}}, "dest": {"index": "inews2022-12-04"}}
